---
- hosts: barmaglot
  
  vars_prompt:

    - name: app_dir
      prompt: "Please enter the app_dir"
      private: no

  tasks:

   - debug:
       msg: "Running playbook as {{ lookup('env', 'USER') }} ..."

   - name: Install Python
     sudo: yes
     sudo_user: "{{ lookup('env', 'USER') }}"
     command: chdir={{ app_dir }} sh bin/install_python3_5.sh >> dev_build.log 
     register: install_stdout
     
   - debug:
       msg: "{{ install_stdout.stdout }}"
