---
- hosts: barmaglot

  vars:
      current_sudo_user: "{{ lookup('env', 'USER') }}"

  vars_prompt:

    - name: virtualenv_dir
      prompt: "Please enter the virtualenv_dir"
      private: no

    - name: app_dir
      prompt: "Please enter the app_dir"
      private: no

  tasks:

    - name: Install Git
      sudo: yes
      apt: pkg=git state=installed update_cache=true

    - name: Install Foreign Function Interface library
      sudo: yes
      apt: pkg=libffi-dev state=installed update_cache=true

    - name: Install Virtual Env
      become: yes
      apt: pkg=virtualenv state=installed update_cache=true
      notify:
      - Initiate virtualenv
      - Install requirements

    - name: Install NodeJS
      sudo: yes
      apt: pkg=nodejs state=installed update_cache=true

    - name: Install NPM
      sudo: yes
      apt: pkg=npm state=installed update_cache=true
      notify:
      - Install NPM packages
      - Building Webpack Dev build

  handlers:
    - name: Initiate virtualenv
      become: yes
      become_user: "{{ current_sudo_user }}"
      command: virtualenv {{ virtualenv_dir }} -p python3.5 creates="{{ virtualenv_dir }}"

    - name: Install requirements
      become: yes
      become_user: "{{ current_sudo_user }}"
      pip:
        requirements={{ app_dir }}/requirements.txt
        executable={{ virtualenv_dir }}/bin/pip3

    - name: Install NPM packages
      npm:
        path={{ app_dir }}

    - name: Building Webpack Dev build
      shell: cd {{ app_dir }}; sh {{ app_dir }}/build_js.sh >> dev_build_js.log
